name: Finish-Feature
on:
  push:
    branches:
      - feature/*
jobs:
  jobMergeDesarrolloToFeature:
    name: Merge-Desarrollo-To-Feature
    outputs:
      rama-feature: ${{steps.get-vars.outputs.rama-feature}}
    runs-on: ubuntu-latest
    steps:
      - id: checkOut
        uses: actions/checkout@v2
      - id: get-vars
        run:
          echo "::set-output name=rama-feature::$(echo ${GITHUB_REF#refs/heads/})"
      - id: merge-to-feature
        name: merge-to-feature
        uses: tukasz/direct-merge-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          source-branch: develop
          target-branch: ${{steps.get-vars.outputs.rama-feature}}


  jobMergeFeatureToDesarrollo:
    name: Merge-Feature-To-Desarrollo
    needs: jobMergeDesarrolloToFeature
    runs-on: ubuntu-latest
    steps:
      - id: checkOut
        uses: actions/checkout@v2
      - id: merge-to-feature
        name: merge-to-feature
        uses: tukasz/direct-merge-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          source-branch:  ${{needs.jobMergeDesarrolloToFeature.outputs.rama-feature}}
          target-branch: develop

  jobCreateRelease:
    name: Create-Release
    needs: jobMergeFeatureToDesarrollo
    if: "${{ contains(github.event.head_commit.message, '#RELEASE') }}"
    runs-on: ubuntu-latest
    steps:
      - id: checkOut
        uses: actions/checkout@v3
        with:
          ref: develop
      - id: create-release
        name: Create release branch
        run: |
          git checkout develop
          git checkout -b release/new-release
      - name: Initialize mandatory git config
        run: |
          git config user.name "GitHub Actions Automation"
          git config user.email noreply@github.com
      - name: Push new branch
        run: git push origin release/new-release
      - name: Validar resultado con errores
        if: ${{ failure() }}
        env:
          MENSAJE_ERROR: Fallo la creación del Release
        run: echo "::set-output name=respuesta-release::${MENSAJE_ERROR}"
      - name: Validar resultado sin errores
        if: ${{ success() }}
        env:
          MENSAJE_EXITO: Se creo la rama Release release/new-release
        run: echo "::set-output name=respuesta-release::${MENSAJE_EXITO}"
